[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "AI for Poetry Writing: Techniques and Strategies for More Innovative and Inspiring Poem Creation with Machine Learning"
